---
# tasks file for Desktop
- name: Install basic packages for Desktop
  package: name={{ item }} state=present
  with_items:
    - git-all
    - lsyncd #https://axkibe.github.io/lsyncd/
    - tree #https://www.computerhope.com/unix/tree.htm
    - ncdu #https://www.binarytides.com/check-disk-usage-linux-ncdu/
    - rsync
    - megacmd
    - virtualbox
  register: result_install_packages_desktop
  tags:
    - basic_packages_desktop
  notify:
    -  Update cache
- name: Install Python modules
  command: pip3 install mysql-connector docker
  register: result_install_pymodules_desktop
  tags:
    - pip_specific_desktop
- meta: flush_handlers        
- debug: msg="{{ result_install_packages_desktop|default("nothing was installed") }}"
  tags:
    - debug_packages_desktop


