---
-
 hosts: server
 gather_facts: True
 tasks:
    - name: Install basic packages
      package: 
        name:
        - net-tools
        - ssmtp
        - beets
        - mdadm
        - fail2ban
        - ssh
        - python3
        - python3-pip
        - ffmpeg
        - rkhunter
        - lsyncd
        - tree
        state: present
      register: result_install_packages
      tags:
        - basic_packages 
      notify:
        - Update cache
    - debug: msg="{{ result_install_packages|default("nothing to install") }}"
      tags:
        - debug_packages   
    - meta: flush_handlers
    - name: Overwrite ssmtp file to /etc/ssmtp/ssmtp.conf
      copy:
        src: ./files/ssmtp.conf
        dest: /etc/ssmtp
        owner: slashviper
        group: slashviper
        mode: 0600
        register: result_copy_ssmtp
        tags:
          - ssmtp.conf
    - name: Test if mailing system works
      command: mdadm --monitor --scan --test --oneshot
      tags:
        - test_smtp
    - name: Install Python modules
      command: pip3 install mysql-connector eyeD3 -U spotdl
      register: result_install_pymods
      tags:
        - pip_specific_nas
    - name: Create issues.net file
      copy:
        src: ./files/issues.net
        dest: /etc
        owner: slashviper
        group: slashviper
        mode: 0600
        tags:
          - banner
    - name: Install Docker
      command: curl -ssl https://get.docker.com/ | sh
      register: result_install_docker
      tags:
        - install_docker
    - debug: msg="{{ result_install_docker|default("nothing to install") }}"
      tags:
        - debug_docker
    - name: Add user todocker group
      command: usermod -aG docker $USER
    - name: Docker pull Plex
      docker_image:
       name: plexinc/pms-docker
      tags:
        - docker_plex
    - name: Docker pull MariaDB
      docker_image:
       name: mariadb
      tags:
        - docker_mariadb
    - name: Docker pull SpotifyDL
      docker_image: 
       name: ritiek/spotify-downloader
      tags:
        - docker_spdl
    - name: Docker pull MineCraft BedRock Server
      docker_image: 
       name: minecraft-bedrock-server
      tags:
        - docker_minecraft
    - name: Create specific folders
      command: mkdir {{ items }} state=present
      with_items:
        - /mnt/raid1/Plexdb
        - /mnt/raid1/MariaDb
        - /mnt/raid1/PlexTranscode
        - ~/.messages
      tags:
        - nas specific folders
    - name: Launch container MC
      command: docker run -d -it -e EULA=TRUE -p 19132:19132/udp --name mc --restart unless-stopped itzg/minecraft-bedrock-server
      tags:
        - docker_minecraft
    - name: Launch container Plex
      command: docker run -d --name plex --network=host --restart unless-stopped -e TZ="Europe/Amsterdam" -e PLEX_CLAIM="claim-rsC1RGXAm3LJ3z7dW7Hn" -e PLEX_UID="1000" -e PLEX_GID="1000" -h PlexServer -v /mnt/raid1/Plexdb:/config -v /mnt/raid1/PlexTranscode:/transcode -v /mnt/raid1/Plex:/data plex_latest
      tags:
        - docker_plex
    - name: Launch container MariaDB
      command: docker run -d --name mariadb -p 3307:3306 --restart unless-stopped -v db:/var/lib/mysql -e MYSQL_ROOT_PASSWORD={ mariadb_rootpwd } -e MYSQL_PASSWORD={ mariadb_userpwd } -e MYSQL_DATABASE=nextcloud -e MYSQL_USER=nextcloud -e MYSQL_HOST=nextcloud mariadb_latest
      tags:
        - docker_mariadb
    - name: Launch container NextCloud
      command: docker run -d --name nextcloud -p 8080:80 --restart unless-stopped -v apps:/var/www/html/custom_apps -v config:/var/www/html/config -v data:/var/www/data -v nextcloud:/var/www/html nextcloud
      tags:
        - docker_nextcloud
 handlers:
    - name: Update cache
      apt:
        update_cache: True
      tags:
        - update_cache