---
-
 hosts: server
 gather_facts: True
 tasks:
    - name: Install basic packages
      apt: name= "{{ item }}" state=present
      with_items:
       - net-tools
       - ssmtp
       - beets
       - mdadm
       - fail2ban
       - ssh
       - python3
       - python3-pip
       - ffmpeg
       - rkhunter
      tags:
        - basic_packages 
    - name: Update cache
      apt:
        update_cache: True
      tags:
        - update_cache
...
