---
# tasks file for Security
- name: Install basic packages Security
  package: name={{ item }} state=present
  with_items:
    - net-tools #https://linuxx.info/net-tools/
    - ssmtp #https://linuxhandbook.com/linux-send-email-ssmtp/
    - fail2ban #https://linuxhandbook.com/fail2ban-basic/
    - ssh 
    - python3 
    - python3-pip 
    - rkhunter #https://help.ubuntu.com/community/RKhunter
  register: result_install_packages_sec
  tags:
    - basic_packages_sec 
  notify:
    - Update cache
- meta: flush_handlers        
- debug: msg="{{ result_install_packages_sec|default("nothing was installed") }}"
  tags:
    - debug_packages_sec
- name: Overwrite ssmtp file to {{ ssmtp_dest }}
  copy:
    src: ssmtp.conf
    dest: "{{ ssmtp_dest }}"
- name: Create issues.net file in {{ banner_target }}
  copy:
    src: issues.net
    dest: "{{ banner_target }}"
    tags:
      - banner